sudo: required

services: 
  - docker

script:
  - docker build -t latifdev/node .
  - docker images latifdev/node

before_deploy:
  docker login -u latifdev -p Knowseeker2019>

deploy:
  provider: script
  script: docker push latifdev/node
  on: 
    branch: master
